
---

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create

  output:
    ansi:
      enabled: always
  instancio:
    bean:
      validation:
        enabled: true
  sql:
    init:
      mode: always
  profiles:
    default: dev

logging:
  level:
    root: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
    pretty-print: true

sentry:
  dsn: https://fd32e85ab59727ffc59ace24cdc2452a@o4508788377714688.ingest.de.sentry.io/4508788501774416
  traces-sample-rate: 1.0

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
